// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConfigStore is an autogenerated mock type for the ConfigStore type
type ConfigStore struct {
	mock.Mock
}

// Set provides a mock function with given fields: updates
func (_m *ConfigStore) Set(updates map[string]interface{}) error {
	ret := _m.Called(updates)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) error); ok {
		r0 = rf(updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConfigStore creates a new instance of ConfigStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigStore {
	mock := &ConfigStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
