// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TypePersister is an autogenerated mock type for the TypePersister type
type TypePersister struct {
	mock.Mock
}

// PersistControllerType provides a mock function with given fields: t
func (_m *TypePersister) PersistControllerType(t string) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for PersistControllerType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTypePersister creates a new instance of TypePersister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTypePersister(t interface {
	mock.TestingT
	Cleanup(func())
}) *TypePersister {
	mock := &TypePersister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
