// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "github.com/adrianozp/gaardrail/app/entities"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// GetParams provides a mock function with no fields
func (_m *Controller) GetParams() entities.ControllerParams {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetParams")
	}

	var r0 entities.ControllerParams
	if rf, ok := ret.Get(0).(func() entities.ControllerParams); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entities.ControllerParams)
	}

	return r0
}

// SetParams provides a mock function with given fields: p
func (_m *Controller) SetParams(p entities.ControllerParams) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for SetParams")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.ControllerParams) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Type provides a mock function with no fields
func (_m *Controller) Type() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
