// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "github.com/adrianozp/gaardrail/app/entities"

	mock "github.com/stretchr/testify/mock"
)

// CreateMessageUseCase is an autogenerated mock type for the CreateMessageUseCase type
type CreateMessageUseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *CreateMessageUseCase) Create(_a0 entities.Message) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Message) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(entities.Message) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(entities.Message) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCreateMessageUseCase creates a new instance of CreateMessageUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateMessageUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateMessageUseCase {
	mock := &CreateMessageUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
