// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/adrianozp/gaardrail/app/entities"
	mock "github.com/stretchr/testify/mock"
)

// ResponseQueue is an autogenerated mock type for the ResponseQueue type
type ResponseQueue struct {
	mock.Mock
}

// Enqueue provides a mock function with given fields: _a0, _a1
func (_m *ResponseQueue) Enqueue(_a0 context.Context, _a1 entities.Response) {
	_m.Called(_a0, _a1)
}

// NewResponseQueue creates a new instance of ResponseQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResponseQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResponseQueue {
	mock := &ResponseQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
