// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/adrianozp/gaardrail/app/entities"
	mock "github.com/stretchr/testify/mock"
)

// SourceQueue is an autogenerated mock type for the SourceQueue type
type SourceQueue struct {
	mock.Mock
}

// Ack provides a mock function with given fields: _a0, _a1
func (_m *SourceQueue) Ack(_a0 context.Context, _a1 entities.Message) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Message) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Dequeue provides a mock function with given fields: _a0
func (_m *SourceQueue) Dequeue(_a0 context.Context) (entities.Message, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Dequeue")
	}

	var r0 entities.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (entities.Message, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) entities.Message); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(entities.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Size provides a mock function with no fields
func (_m *SourceQueue) Size() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSourceQueue creates a new instance of SourceQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSourceQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *SourceQueue {
	mock := &SourceQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
