// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SwitchControllerUseCase is an autogenerated mock type for the SwitchControllerUseCase type
type SwitchControllerUseCase struct {
	mock.Mock
}

// Current provides a mock function with no fields
func (_m *SwitchControllerUseCase) Current() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Switch provides a mock function with given fields: t
func (_m *SwitchControllerUseCase) Switch(t string) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Switch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSwitchControllerUseCase creates a new instance of SwitchControllerUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSwitchControllerUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SwitchControllerUseCase {
	mock := &SwitchControllerUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
