// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "github.com/adrianozp/gaardrail/app/entities"
	mock "github.com/stretchr/testify/mock"
)

// ProcessMetrics is an autogenerated mock type for the ProcessMetrics type
type ProcessMetrics struct {
	mock.Mock
}

// Process provides a mock function with given fields: m
func (_m *ProcessMetrics) Process(m entities.Metrics) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.Metrics) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProcessMetrics creates a new instance of ProcessMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessMetrics {
	mock := &ProcessMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
