// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// Compute provides a mock function with given fields: measured, measureTime
func (_m *Controller) Compute(measured float64, measureTime time.Time) (float64, error) {
	ret := _m.Called(measured, measureTime)

	if len(ret) == 0 {
		panic("no return value specified for Compute")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(float64, time.Time) (float64, error)); ok {
		return rf(measured, measureTime)
	}
	if rf, ok := ret.Get(0).(func(float64, time.Time) float64); ok {
		r0 = rf(measured, measureTime)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(float64, time.Time) error); ok {
		r1 = rf(measured, measureTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
