// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// QueryHolder is an autogenerated mock type for the QueryHolder type
type QueryHolder struct {
	mock.Mock
}

// Query provides a mock function with no fields
func (_m *QueryHolder) Query() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetQuery provides a mock function with given fields: _a0
func (_m *QueryHolder) SetQuery(_a0 string) {
	_m.Called(_a0)
}

// NewQueryHolder creates a new instance of QueryHolder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryHolder(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryHolder {
	mock := &QueryHolder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
