// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "github.com/adrianozp/gaardrail/app/entities"

	mock "github.com/stretchr/testify/mock"
)

// ControllerParamsUseCase is an autogenerated mock type for the ControllerParamsUseCase type
type ControllerParamsUseCase struct {
	mock.Mock
}

// CurrentType provides a mock function with no fields
func (_m *ControllerParamsUseCase) CurrentType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrentType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Get provides a mock function with no fields
func (_m *ControllerParamsUseCase) Get() entities.ControllerParams {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entities.ControllerParams
	if rf, ok := ret.Get(0).(func() entities.ControllerParams); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entities.ControllerParams)
	}

	return r0
}

// Update provides a mock function with given fields: p
func (_m *ControllerParamsUseCase) Update(p entities.ControllerParams) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.ControllerParams) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewControllerParamsUseCase creates a new instance of ControllerParamsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewControllerParamsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ControllerParamsUseCase {
	mock := &ControllerParamsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
